## 1 Extract

In [163]:
import pyodbc
import pandas as pd
from datetime import datetime

In [164]:
import pyodbc
#print(pyodbc.drivers())

In [199]:
source_conn=pyodbc.connect(
    "Driver={ODBC Driver 17 for SQL Server};"
    "Server=DESKTOP-1I9V7A2\\SQLEXPRESS;"
    "Database=Sales_OLTP;"
    "Trusted_Connection=Yes;"
)

In [166]:
df_product=pd.read_sql("""
                       select * from product p left outer join  SubCategory sc 
                        on p.SubCategoryID = sc.SubCategoryID
                        left outer join category ct
                        on sc.CategoryID=ct.CategoryID
                       
                       """,source_conn)
df_product

C:\Users\Ahmed alqadi\AppData\Local\Temp\ipykernel_26152\909063652.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_product=pd.read_sql("""

,ProductID,ProductName,SubCategoryID,Price,LastModifiedDate,is_current,SubCategoryID,SubCategoryName,CategoryID,LastModifiedDate,is_current,CategoryID,CategoryName,LastModifiedDate,is_current
0,1,"HL Road Frame - Black, 588",14,1431.50,2014-02-08 10:01:36.827,True,14,Road Frames,2,2008-04-30,True,2,Components,2008-04-30,True
1,2,"HL Road Frame - Red, 58",14,1431.50,2014-02-08 10:01:36.827,True,14,Road Frames,2,2008-04-30,True,2,Components,2008-04-30,True
2,3,"Sport-100 Helmet, Red",31,34.99,2014-02-08 10:01:36.827,True,31,Helmets,4,2008-04-30,True,4,Accessories,2008-04-30,True
3,4,"Sport-100 Helmet, Black",31,34.99,2014-02-08 10:01:36.827,True,31,Helmets,4,2008-04-30,True,4,Accessories,2008-04-30,True
4,5,"Mountain Bike Socks, M",23,9.50,2014-02-08 10:01:36.827,True,23,Socks,3,2008-04-30,True,3,Clothing,2008-04-30,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,71,Water Bottle - 30 oz.,28,4.99,2014-02-08 10:01:36.827,True,28,Bottles and Cages,4,2008-04-30,True,4,Accessories,2008-04-30,True
71,72,Patch Kit/8 Patches,37,2.29,2014-02-08 10:01:36.827,True,37,Tires and Tubes,4,2008-04-30,True,4,Accessories,2008-04-30,True
72,73,Mountain Tire Tube,37,4.99,2014-02-08 10:01:36.827,True,37,Tires and Tubes,4,2008-04-30,True,4,Accessories,2008-04-30,True
73,74,Road Tire Tube,37,3.99,2014-02-08 10:01:36.827,True,37,Tires and Tubes,4,2008-04-30,True,4,Accessories,2008-04-30,True
74,75,Touring Tire Tube,37,4.99,2014-02-08 10:01:36.827,True,37,Tires and Tubes,4,2008-04-30,True,4,Accessories,2008-04-30,True

In [167]:
df_customer=pd.read_sql("select * from Vcustomer" , source_conn)
df_customer

C:\Users\Ahmed alqadi\AppData\Local\Temp\ipykernel_26152\1483734206.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_customer=pd.read_sql("select * from Vcustomer" , source_conn)

,CustomerID,FirstName,LastName,Email,PhoneNumber,GenderID,LastModifiedDate,is_current,GenderName
0,1,John,Doe,john.doe@email.com,123-456-7890,1,2023-01-01,True,Male
1,2,Jane,Smith,jane.smith@email.com,987-654-3210,2,2023-01-01,True,Female
2,3,Alice,Johnson,alice.johnson@email.com,111-222-3333,3,2023-01-01,True,Other
3,4,Bob,Smith,bob.smith@email.com,444-555-6666,1,2023-01-01,True,Male
4,5,Eva,Davis,eva.davis@email.com,777-888-9999,2,2023-01-01,True,Female
5,6,Michael,Williams,michael.williams@email.com,555-111-2222,1,2023-01-01,True,Male
6,7,Sophia,Brown,sophia.brown@email.com,555-333-4444,2,2023-01-01,True,Female
7,8,Oliver,Jones,oliver.jones@email.com,555-555-6666,1,2023-01-01,True,Male
8,9,Emma,Garcia,emma.garcia@email.com,555-777-8888,2,2023-01-01,True,Female
9,10,Jackson,Martinez,jackson.martinez@email.com,555-999-0000,1,2023-01-01,True,Male

In [168]:
df_salesman=pd.read_sql("select * from Vsalesman" , source_conn)
df_salesman

C:\Users\Ahmed alqadi\AppData\Local\Temp\ipykernel_26152\4121669342.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_salesman=pd.read_sql("select * from Vsalesman" , source_conn)

,SalesmanID,FirstName,LastName,Email,PhoneNumber,AddressID,LastModifiedDate,is_current,City,State,ZipCode
0,1,Mike,Johnson,mike.johnson@email.com,555-123-4567,1,2023-01-01,True,Cityville,CA,12345
1,2,Emily,Taylor,emily.taylor@email.com,555-222-3333,2,2023-01-01,True,Townsville,NY,67890
2,3,William,Johnson,william.johnson@email.com,555-444-5555,1,2023-01-01,True,Cityville,CA,12345
3,4,Ava,Davis,ava.davis@email.com,555-666-7777,3,2023-01-01,True,Villageton,TX,45678
4,5,Ethan,Miller,ethan.miller@email.com,555-888-9999,1,2023-01-01,True,Cityville,CA,12345
5,6,Sophie,Anderson,sophie.anderson@email.com,555-000-1111,2,2023-01-01,True,Townsville,NY,67890

In [200]:
df_order=pd.read_sql("""
                  select o.*,os.Quantity,os.TotalPrice,os.OrderDetailsID,os.ProductID
from Orders o 
left outer join OrderDetails os
on o.OrderID=os.OrderID
                     """ , source_conn)
df_order

C:\Users\Ahmed alqadi\AppData\Local\Temp\ipykernel_26152\1957570954.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_order=pd.read_sql("""

,OrderID,CustomerID,SalesmanID,OrderDate,LastModifiedDate,is_current,Quantity,TotalPrice,OrderDetailsID,ProductID
0,1,3,4,2023-01-01 10:00:00,2023-01-01 10:00:00,True,3,1011.66,1,22
1,1,3,4,2023-01-01 10:00:00,2023-01-01 10:00:00,True,5,7157.50,2,15
2,1,3,4,2023-01-01 10:00:00,2023-01-01 10:00:00,True,6,8589.00,3,1
3,2,8,6,2023-01-01 11:30:00,2023-01-01 11:30:00,True,4,139.96,4,7
4,2,8,6,2023-01-01 11:30:00,2023-01-01 11:30:00,True,22,31493.00,5,13
5,3,3,6,2023-01-02 08:45:00,2023-01-02 08:45:00,True,7,2360.54,6,33
6,4,3,6,2023-01-02 09:15:00,2023-01-02 09:15:00,True,3,149.97,7,9
7,4,3,6,2023-01-02 09:15:00,2023-01-02 09:15:00,True,5,249.95,8,10
8,5,5,4,2023-01-02 12:20:00,2023-01-02 12:20:00,True,3,104.97,9,4
9,6,1,2,2023-02-07 11:30:00,2023-01-07 11:30:00,True,2,7156.54,10,45
10,6,1,2,2023-02-07 11:30:00,2023-01-07 11:30:00,True,5,249.95,11,12
11,6,1,2,2023-02-07 11:30:00,2023-01-07 11:30:00,True,4,139.96,12,7
12,7,2,4,2023-02-07 13:45:00,2023-01-07 13:45:00,True,1,337.22,13,34
13,8,8,3,2023-02-07 15:00:00,2023-01-07 15:00:00,True,2,69.98,14,4
14,9,6,1,2023-03-03 13:10:00,2023-03-03 13:10:00,True,3,4048.80,15,39
15,10,2,6,2023-04-08 11:25:00,2023-04-08 11:25:00,True,6,8747.94,16,52
16,11,3,2,2023-04-08 12:00:00,2023-04-08 12:00:00,True,5,16999.95,17,70
17,11,3,2,2023-04-08 12:00:00,2023-04-08 12:00:00,True,8,6263.92,18,57
18,11,3,2,2023-04-08 12:00:00,2023-04-08 12:00:00,True,2,1565.98,19,63
19,11,3,2,2023-04-08 12:00:00,2023-04-08 12:00:00,True,1,1349.60,20,43

In [201]:
source_conn.close()

## 2.Transform

In [171]:
df_temp=df_product.copy()

In [172]:
df_temp

,ProductID,ProductName,SubCategoryID,Price,LastModifiedDate,is_current,SubCategoryID,SubCategoryName,CategoryID,LastModifiedDate,is_current,CategoryID,CategoryName,LastModifiedDate,is_current
0,1,"HL Road Frame - Black, 588",14,1431.50,2014-02-08 10:01:36.827,True,14,Road Frames,2,2008-04-30,True,2,Components,2008-04-30,True
1,2,"HL Road Frame - Red, 58",14,1431.50,2014-02-08 10:01:36.827,True,14,Road Frames,2,2008-04-30,True,2,Components,2008-04-30,True
2,3,"Sport-100 Helmet, Red",31,34.99,2014-02-08 10:01:36.827,True,31,Helmets,4,2008-04-30,True,4,Accessories,2008-04-30,True
3,4,"Sport-100 Helmet, Black",31,34.99,2014-02-08 10:01:36.827,True,31,Helmets,4,2008-04-30,True,4,Accessories,2008-04-30,True
4,5,"Mountain Bike Socks, M",23,9.50,2014-02-08 10:01:36.827,True,23,Socks,3,2008-04-30,True,3,Clothing,2008-04-30,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,71,Water Bottle - 30 oz.,28,4.99,2014-02-08 10:01:36.827,True,28,Bottles and Cages,4,2008-04-30,True,4,Accessories,2008-04-30,True
71,72,Patch Kit/8 Patches,37,2.29,2014-02-08 10:01:36.827,True,37,Tires and Tubes,4,2008-04-30,True,4,Accessories,2008-04-30,True
72,73,Mountain Tire Tube,37,4.99,2014-02-08 10:01:36.827,True,37,Tires and Tubes,4,2008-04-30,True,4,Accessories,2008-04-30,True
73,74,Road Tire Tube,37,3.99,2014-02-08 10:01:36.827,True,37,Tires and Tubes,4,2008-04-30,True,4,Accessories,2008-04-30,True
74,75,Touring Tire Tube,37,4.99,2014-02-08 10:01:36.827,True,37,Tires and Tubes,4,2008-04-30,True,4,Accessories,2008-04-30,True

In [173]:
df_dim_product=pd.DataFrame()

In [177]:
df_temp.columns

Index(['ProductID', 'ProductName', 'SubCategoryID', 'Price',
       'LastModifiedDate', 'is_current', 'SubCategoryID', 'SubCategoryName',
       'CategoryID', 'LastModifiedDate', 'is_current', 'CategoryID',
       'CategoryName', 'LastModifiedDate', 'is_current'],
      dtype='object')

In [176]:
df_dim_product['product_sk']=None
df_dim_product['product_Bk']=df_temp['ProductID']
df_dim_product['product_Name']=df_temp['ProductName'].str.strip()
df_dim_product['Subcategory_Bk']=df_temp['SubCategoryID'].iloc[:, 0].values
df_dim_product['price']=df_temp['Price'] .astype('float') .fillna(0)
df_dim_product['Subcategory_Name']=df_temp['SubCategoryName'] 
df_dim_product['Category_Bk']=df_temp['CategoryID'].iloc[:, 0].values
df_dim_product['Category_Name']=df_temp['CategoryName']

In [178]:
df_dim_product

,product_sk,product_Bk,product_Name,Subcategory_Bk,price,Subcategory_Name,Category_Bk,Category_Name
0,None,1,"HL Road Frame - Black, 588",14,1431.50,Road Frames,2,Components
1,None,2,"HL Road Frame - Red, 58",14,1431.50,Road Frames,2,Components
2,None,3,"Sport-100 Helmet, Red",31,34.99,Helmets,4,Accessories
3,None,4,"Sport-100 Helmet, Black",31,34.99,Helmets,4,Accessories
4,None,5,"Mountain Bike Socks, M",23,9.50,Socks,3,Clothing
...,...,...,...,...,...,...,...,...
70,None,71,Water Bottle - 30 oz.,28,4.99,Bottles and Cages,4,Accessories
71,None,72,Patch Kit/8 Patches,37,2.29,Tires and Tubes,4,Accessories
72,None,73,Mountain Tire Tube,37,4.99,Tires and Tubes,4,Accessories
73,None,74,Road Tire Tube,37,3.99,Tires and Tubes,4,Accessories
74,None,75,Touring Tire Tube,37,4.99,Tires and Tubes,4,Accessories

In [179]:
df_temp=df_salesman.copy()
df__dim_salesman=pd.DataFrame()
df_temp.columns

Index(['SalesmanID', 'FirstName', 'LastName', 'Email', 'PhoneNumber',
       'AddressID', 'LastModifiedDate', 'is_current', 'City', 'State',
       'ZipCode'],
      dtype='object')

In [180]:
df__dim_salesman['Salesman_sk']=None
df__dim_salesman['Salesman_Bk']=df_temp['SalesmanID']
df__dim_salesman['Fname']=df_temp['FirstName']
df__dim_salesman['Lname']=df_temp['LastName']
df__dim_salesman['Email']=df_temp['Email'] 
df__dim_salesman['Phone']=df_temp['PhoneNumber'] 
df__dim_salesman['Address_Bk']=df_temp['AddressID']
df__dim_salesman['City']=df_temp['City']
df__dim_salesman['State']=df_temp['State']
df__dim_salesman['ZipCode']=df_temp['ZipCode']

In [181]:
df__dim_salesman

,Salesman_sk,Salesman_Bk,Fname,Lname,Email,Phone,Address_Bk,City,State,ZipCode
0,NaN,1,Mike,Johnson,mike.johnson@email.com,555-123-4567,1,Cityville,CA,12345
1,NaN,2,Emily,Taylor,emily.taylor@email.com,555-222-3333,2,Townsville,NY,67890
2,NaN,3,William,Johnson,william.johnson@email.com,555-444-5555,1,Cityville,CA,12345
3,NaN,4,Ava,Davis,ava.davis@email.com,555-666-7777,3,Villageton,TX,45678
4,NaN,5,Ethan,Miller,ethan.miller@email.com,555-888-9999,1,Cityville,CA,12345
5,NaN,6,Sophie,Anderson,sophie.anderson@email.com,555-000-1111,2,Townsville,NY,67890

In [182]:
df_temp=df_customer.copy()
df_dim_customer=pd.DataFrame()
df_temp.columns

Index(['CustomerID', 'FirstName', 'LastName', 'Email', 'PhoneNumber',
       'GenderID', 'LastModifiedDate', 'is_current', 'GenderName'],
      dtype='object')

In [184]:
df_dim_customer['Customer_sk']=None
df_dim_customer['Customer_Bk']=df_temp['CustomerID']
df_dim_customer['Fname']=df_temp['FirstName'].str.capitalize()
df_dim_customer['Lname']=df_temp['LastName'].str.capitalize()
df_dim_customer['Email']=df_temp['Email'] .str.strip()
df_dim_customer['Phone']=df_temp['PhoneNumber'] 
df_dim_customer['Gender_BK']=df_temp['GenderID']
df_dim_customer['GenderName']=df_temp['GenderName']

In [185]:
df_dim_customer

,Customer_sk,Customer_Bk,Fname,Lname,Email,Phone,Gender_BK,GenderName
0,None,1,John,Doe,john.doe@email.com,123-456-7890,1,Male
1,None,2,Jane,Smith,jane.smith@email.com,987-654-3210,2,Female
2,None,3,Alice,Johnson,alice.johnson@email.com,111-222-3333,3,Other
3,None,4,Bob,Smith,bob.smith@email.com,444-555-6666,1,Male
4,None,5,Eva,Davis,eva.davis@email.com,777-888-9999,2,Female
5,None,6,Michael,Williams,michael.williams@email.com,555-111-2222,1,Male
6,None,7,Sophia,Brown,sophia.brown@email.com,555-333-4444,2,Female
7,None,8,Oliver,Jones,oliver.jones@email.com,555-555-6666,1,Male
8,None,9,Emma,Garcia,emma.garcia@email.com,555-777-8888,2,Female
9,None,10,Jackson,Martinez,jackson.martinez@email.com,555-999-0000,1,Male

## 3.Load

In [186]:
dwh_conn=pyodbc.connect(
    "Driver={ODBC Driver 17 for SQL Server};"
    "Server=DESKTOP-1I9V7A2\\SQLEXPRESS;"
    "Database=Saledwh1;"
    "Trusted_Connection=Yes;"
)
dwh_cursor=dwh_conn.cursor()

In [187]:
for index, row in df_dim_product.iterrows():
    dwh_cursor.execute(
       """
       insert into dim_produt values(?,?,?,?,?,?,?)
       """
       , 
       row['product_Bk'],
       row['product_Name'],
       row['Subcategory_Bk'],
       row['Subcategory_Name'],
       row['Category_Bk'],
       row['Category_Name'],
       row['price'],
    
    )
    dwh_conn.commit()

In [188]:
df__dim_salesman.columns

Index(['Salesman_sk', 'Salesman_Bk', 'Fname', 'Lname', 'Email', 'Phone',
       'Address_Bk', 'City', 'State', 'ZipCode'],
      dtype='object')

In [189]:
for index, row in df__dim_salesman.iterrows():
    dwh_cursor.execute(
       """
       insert into dim_salesman values(?,?,?,?,?,?,?,?,?)
       """
       , 
       row['Salesman_Bk'],
       row['Fname'],
       row['Lname'],
       row['Email'],
       row['Phone'],
       row['Address_Bk'],
       row['City'],
       row['State'],
       row['ZipCode'],
    
    )
    dwh_conn.commit()

In [190]:
df_dim_customer.columns

Index(['Customer_sk', 'Customer_Bk', 'Fname', 'Lname', 'Email', 'Phone',
       'Gender_BK', 'GenderName'],
      dtype='object')

In [191]:
for index, row in df_dim_customer.iterrows():
    dwh_cursor.execute(
       """
       insert into dim_customer values(?,?,?,?,?,?,?)
       """
       , 
       row['Customer_Bk'],
       row['Fname'],
       row['Lname'],
       row['Email'],
        row['Phone'],
       row['Gender_BK'],
       row['GenderName'],
    
    )
    dwh_conn.commit()

In [214]:
df_Fact_Sales=df_order.copy()

In [215]:
df_Fact_Sales.columns

Index(['OrderID', 'CustomerID', 'SalesmanID', 'OrderDate', 'LastModifiedDate',
       'is_current', 'Quantity', 'TotalPrice', 'OrderDetailsID', 'ProductID'],
      dtype='object')

In [216]:
df_Fact_Sales['unite-price'] =( df_Fact_Sales['TotalPrice'] / df_Fact_Sales['Quantity']).astype('float')
df_Fact_Sales['unite-price']

0      337.22
1     1431.50
2     1431.50
3       34.99
4     1431.50
5      337.22
6       49.99
7       49.99
8       34.99
9     3578.27
10      49.99
11      34.99
12     337.22
13      34.99
14    1349.60
15    1457.99
16    3399.99
17     782.99
18     782.99
19    1349.60
Name: unite-price, dtype: float64

In [217]:
df_Fact_Sales['OrderDate_fk']=df_Fact_Sales['OrderDate'].dt.strftime('%Y%m%d')
df_Fact_Sales['OrderDate_fk']

0     20230101
1     20230101
2     20230101
3     20230101
4     20230101
5     20230102
6     20230102
7     20230102
8     20230102
9     20230207
10    20230207
11    20230207
12    20230207
13    20230207
14    20230303
15    20230408
16    20230408
17    20230408
18    20230408
19    20230408
Name: OrderDate_fk, dtype: object

In [218]:
df_Fact_Sales=df_Fact_Sales[['OrderID', 'CustomerID', 'SalesmanID', 'OrderDate_fk', 'Quantity','unite-price', 'TotalPrice', 'OrderDetailsID','ProductID']]

In [ ]:
df_Fact_Sales.columns=['Order_BK', 'Customer_BK', 'Salesman_BK', 'OrderDate_fk', 'Quantity','unite-price', 'TotalPrice', 'OrderDetails_BK','Product_BK']
df_Fact_Sales

,Order_BK,Customer_BK,Salesman_BK,OrderDate_fk,Quantity,unite-price,TotalPrice,OrderDetails_BK,Product_BK
0,1,3,4,20230101,3,337.22,1011.66,1,22
1,1,3,4,20230101,5,1431.50,7157.50,2,15
2,1,3,4,20230101,6,1431.50,8589.00,3,1
3,2,8,6,20230101,4,34.99,139.96,4,7
4,2,8,6,20230101,22,1431.50,31493.00,5,13
5,3,3,6,20230102,7,337.22,2360.54,6,33
6,4,3,6,20230102,3,49.99,149.97,7,9
7,4,3,6,20230102,5,49.99,249.95,8,10
8,5,5,4,20230102,3,34.99,104.97,9,4
9,6,1,2,20230207,2,3578.27,7156.54,10,45
10,6,1,2,20230207,5,49.99,249.95,11,12
11,6,1,2,20230207,4,34.99,139.96,12,7
12,7,2,4,20230207,1,337.22,337.22,13,34
13,8,8,3,20230207,2,34.99,69.98,14,4
14,9,6,1,20230303,3,1349.60,4048.80,15,39
15,10,2,6,20230408,6,1457.99,8747.94,16,52
16,11,3,2,20230408,5,3399.99,16999.95,17,70
17,11,3,2,20230408,8,782.99,6263.92,18,57
18,11,3,2,20230408,2,782.99,1565.98,19,63
19,11,3,2,20230408,1,1349.60,1349.60,20,43

In [226]:
df_dim_product=pd.read_sql("select*from dim_produt",dwh_conn)
df__dim_salesman=pd.read_sql("select*from dim_salesman",dwh_conn)
df_dim_date=pd.read_sql("select*from dim_Date",dwh_conn)
df_dim_customer=pd.read_sql("select*from dim_customer",dwh_conn)

C:\Users\Ahmed alqadi\AppData\Local\Temp\ipykernel_26152\4236320724.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dim_product=pd.read_sql("select*from dim_produt",dwh_conn)
C:\Users\Ahmed alqadi\AppData\Local\Temp\ipykernel_26152\4236320724.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df__dim_salesman=pd.read_sql("select*from dim_salesman",dwh_conn)
C:\Users\Ahmed alqadi\AppData\Local\Temp\ipykernel_26152\4236320724.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dim_date=pd.read_sql("select*from dim_Date",dwh_conn)
C:\Users\Ahmed alqadi\AppData\Local\Temp\ipykernel_26152\4236320724.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dim_customer=pd.read_sql("select*from dim_customer",dwh_conn)

In [ ]:
df_Fact_Sales=pd.merge(df_Fact_Sales,df_dim_product, how='left', on='product_id')

In [238]:
df_Fact_Sales=pd.merge(df_Fact_Sales,df_dim_customer, how='left', on='customer_bk')

KeyError: 'customer_bk'

In [237]:
df_Fact_Sales.columns
df_dim_product.columns
df_dim_customer.columns

Index(['customer_sk', 'customer_bk', 'customer_fname', 'customer_lname',
       'email', 'phone', 'gender_bk', 'gender_name'],
      dtype='object')

In [239]:
df_Fact_Sales = pd.merge(
    df_Fact_Sales, 
    df_dim_customer, 
    how='left', 
    left_on='customer_id',  # الاسم في جدول المبيعات (تأكد من الاسم الصح عندك)
    right_on='customer_bk'  # الاسم في جدول الـ Dimension
)

KeyError: 'customer_id'